name: staging pipeline deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    strategy:
      max-parallel : 4
      matrix:
        python-version: [3.9]
   
    steps:
      - name: clone repo & checkout code
        uses: actions/checkout@v2
     
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with: 
           python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run:  |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python3 -m pip install virtualenv
                 'python3 -m venv venv/
                 . venv/bin/activate
               curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
               python3 get-pip.py --force-reinstall
               pip3 install --user -r requirements.txt
            
      
    
            
           
 
