name: staging pipeline deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      max-parallel : 4
      matrix:
        python-version: [3.9]
   
    steps:
      - name: clone repo & checkout code
        uses: actions/checkout@v2
     
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with: 
           python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run:  |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python3 -m pip install virtualenv
            python3 -m venv venv/
            . venv/bin/activate

      - name: Build 
        run:  |
           touch .docker_env
           cp .env .docker_env
           chmod 400 docker_sh/start.sh
           chmod 400 docker_sh/start-celery-worker.sh
           chmod 400 docker_sh/start-celery-beat.sh
           rm -rf static
           rm -rf templates/static
   
